cc_library(
  name = "quadriflow",
  hdrs = glob(
    ["src/*.hpp"],
    exclude = [
      "src/post-solver.h",
    ],
  ),
  srcs = glob(
    ["src/*.cpp"],
    exclude = [
      "src/post-solver.cpp",
      "src/main.cpp",
    ],
  ),
  defines = [
    "WITH_OMP",
  ],
  deps = [
    "@boost.graph//:boost.graph",
    "@eigen//:eigen",
    "@lemon//:lemon",
    "//3rd/pcg32",
  ],
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "quadriflow_cli",
  srcs = ["src/main.cpp"],
  deps = [
    ":quadriflow",
  ],
  visibility = ["//visibility:public"],
)
