cc_library(
  name = "core",
  hdrs = glob(["*.h"]),
  srcs = ["Solver.cc"],
  include_prefix = "core",
  deps = [
    "//3rd/MapleCOMSPS_LRB/mtl",
    "//3rd/MapleCOMSPS_LRB/utils",
  ],
  visibility = ["//visibility:public"],
)

cc_binary(
  name = "cli",
  srcs = ["Main.cc"],
  deps = [
    "@zlib//:zlib",
    ":core",
  ],
  visibility = ["//visibility:public"],
)
